model: cae_MLP_MNIST
# mask_ratio: 0.974
k: 50
dataset: mnist_fashion
output_dir: outs/outs_MNIST_fashion
log_dir: outs/output_dir_MNIST_fashion
num_workers: 16
batch_size: 128
save_timelapse: False
binarize: False
loss_type: mse
#--------hparams---------
epochs: 200
warmup_epochs: 0
anneal_temp: 'exp'
temp_base: 10
temp_min: 0.01
dim_ip: 0
jsd_factor: 0
blr: 0.001
min_lr: 0.001
batch_accum_iter: 1
pi_dropout: 0
ctp_dropout: 0
gumbel_learn_mode: logits
save_top_k: 1
use_masked_loss: False
anneal_lr: False
scale_lr_by_batchsize: False
